# backend/db/models/chunk.py
"""
Chunk model — retrievable text chunks derived from source files and symbols.

Mirrors the `chunks` table in .ai/DATABASE_SCHEMA.md exactly.

Notes:
- search_vector: GENERATED ALWAYS AS STORED computed column — declared read-only
  in ORM; generated by Alembic migration DDL.
- embedding: VECTOR(1536) from pgvector — declared as a plain Column with
  server-side type; pgvector SQLAlchemy extension is not a runtime dependency
  yet (added when embedding is implemented in Phase 5).  The column type is
  handled via raw DDL in the migration.
"""

import uuid
from datetime import datetime

from sqlalchemy import TIMESTAMP, Computed, ForeignKey, Index, Integer, Text
from sqlalchemy.dialects.postgresql import TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.db.base import Base
from backend.db.types import Vector


class Chunk(Base):
    """A retrievable text chunk from a source file, optionally linked to a symbol."""

    __tablename__ = "chunks"

    __table_args__ = (
        Index("idx_chunks_repository_id", "repository_id"),
        Index("idx_chunks_file_id", "file_id"),
        Index("idx_chunks_symbol_id", "symbol_id"),
        # GIN index on search_vector and IVFFlat index on embedding are created
        # via raw DDL in the Alembic migration.
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default="gen_random_uuid()",
    )
    repository_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("repositories.id", ondelete="CASCADE"),
        nullable=False,
    )
    file_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("files.id", ondelete="CASCADE"),
        nullable=False,
    )
    symbol_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("symbols.id", ondelete="SET NULL"),
        nullable=True,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    start_line: Mapped[int] = mapped_column(Integer, nullable=False)
    end_line: Mapped[int] = mapped_column(Integer, nullable=False)
    token_count: Mapped[int] = mapped_column(Integer, nullable=False)
    # Computed TSVECTOR — read-only from ORM; DDL in migration.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', content)", persisted=True),
        nullable=True,
    )
    embedding: Mapped[list[float] | None] = mapped_column(Vector(1536), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default="now()"
    )

    # Relationships
    repository: Mapped["Repository"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Repository", back_populates="chunks"
    )
    file: Mapped["File"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "File", back_populates="chunks"
    )
    symbol: Mapped["Symbol | None"] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Symbol",
        back_populates="chunks",
        foreign_keys=[symbol_id],
    )
